### ISSUE TITLE
Is it Ok to have a duplicate entry for org.gradle.jvmargs?

### ISSUE THREAD

**Issue by Bilal-Abdeen** [mikehardy/rnfbdemo#8] opened 2022-06-13 22:13 UTC
Thank you very much for this very informative script. I noticed that you add org.gradle.jvmargs statement, instead of updating the existing one. Is this Ok? I mean the following statements. 

```# Another Java build tweak - or gradle runs out of memory during the build
echo "Increasing memory available to gradle for android java build"
echo "org.gradle.jvmargs=-Xmx3072m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> android/gradle.properties```

**Comment by mikehardy** [comment] 2022-06-13 22:24
I guess I had not noticed it since it works in practice - stated differently, before I added that line, the build failed for android, and with the line it worked. So it works in practice, it has a definite effect that you may examine with a positive and a negative test

But it does seem a bit...dirty isn't it? I looked in to it and it turns out that the last definition of a key in a Properties file wins, https://stackoverflow.com/a/20512086/9910298 - given that, I am okay with it, but it would be cleaner to sed the thing out such that the previous line was manipulated instead of just "re-defined"

If you want to play with it and propose a PR, I'll happily merge it, but I won't have time myself and it's working as intended so I'll close the issue

Glad you like the script! So much trial and error is built in to it from when I was first starting my maintainership with react-native-firebase, and now I actually use this all the time for new release testing for react-native in general. It has been useful. Cheers!

**Closed by mikehardy** 2022-06-13 22:24 UTC
